plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.12'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'io.qameta.allure' version '2.11.2'
}

group = 'com.insurance'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.seleniumhq.selenium:selenium-java:4.21.0'
	testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
	implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	testImplementation 'io.qameta.allure:allure-junit5:2.29.0'
}

test {
	useJUnitPlatform()
	systemProperty "allure.results.directory", "build/allure-results"
}

allure {
	version = '2.29.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
